In [1]:
import numpy as np

In [ ]:
# How to Creating a 3x3 Identity Matrix with Float Data Type?
import numpy as np

# Create a 3x3 identity matrix with float data type
identity_matrix = np.eye(3, dtype=float)

# Print the matrix
print("3x3 Identity Matrix with float data type:")
print(identity_matrix)

3x3 Identity Matrix with float data type:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [5]:
np.array([10.3,4.5,7.8,1.0])

array([10.3,  4.5,  7.8,  1. ])

In [6]:
# Reshaping a 1D Array into a 2D Array
# Create a 1D array with 6 elements
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape it into a 2D array (2 rows and 3 columns)
arr_2d = arr_1d.reshape(2, 3)

# Print the reshaped 2D array
print("Reshaped 2D Array:")
print(arr_2d)

Reshaped 2D Array:
[[1 2 3]
 [4 5 6]]


In [8]:
#How to get the common items between two pythons
#NumPy? Input:
a = np. array ([1,2,3,2,3,4,3,4,5,6])
b = np. array ([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a,b)
c

array([2, 4])

In [11]:
#From array a remove all items present in
#array b Input:
a = np. array ([1,2,3,4,5])
b = np. array ([5,6,7,8,9])

result = np.setdiff1d(a, b)
result

array([1, 2, 3, 4])

In [13]:
#Limit the number of items printed in python NumPy array a to a maximum of
#6 elements.
a = np.arange(15)

np.set_printoptions(threshold=6)

# Print the array
print(a)

[ 0  1  2 ... 12 13 14]


In [16]:
#Drop all nan values from a 1D NumPy
#array Input:
a = np. array ([1,2,3, np.nan,5,6,7, np.nan])

a_cleaned = a[~np.isnan(a)]
a_cleaned

array([1., 2., 3., 5., 6., 7.])

In [17]:
# Create a 1D NumPy array of the first 20 natural numbers and a
# 2D NumPy array of shape (4, 5) with values ranging from 1 to 20.
array_1d = np.arange(1, 21)

# 2D array of shape (4, 5) with values ranging from 1 to 20
array_2d = array_1d.reshape(4, 5)
array_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [22]:
# Given a 3D NumPy array of shape (2, 3, 4), find its shape, size,
#number of dimensions, and data type. Change its data type to float64 and verify
#the change.

arr = np.array([[[1,2,3,4],
                [2,6,7,8],
                 [2,3,5,8]],
                [[23,45,67,8],
                [2,5,67,8],
                 [445,7,8,9]]])
arr.shape

(2, 3, 4)

In [24]:
arr.size

24

In [25]:
arr.ndim

3

In [26]:
arr.dtype

dtype('int64')

In [28]:
arr = arr.astype('float64')
arr.dtype

dtype('float64')

In [33]:
ar = np.arange(1,20)
ar

array([ 1,  2,  3, ..., 17, 18, 19])

In [32]:
ar.argsort()

array([ 0,  1,  2, ..., 16, 17, 18])

In [35]:
# Reshape a 1D array of 12 elements into a 3x4 2D array and then
#flatten it back into a 1D array using ravel (). Verify that the flattened array
#matches the original.

# Create a 1D array of 12 elements
original_array = np.arange(12)

# Reshape it into a 3x4 2D array
reshaped_array = original_array.reshape(3, 4)

# Flatten it back into a 1D array using ravel()
flattened_array = reshaped_array.ravel()

# Verify that the flattened array matches the original
arrays_match = np.array_equal(original_array, flattened_array)
arrays_match

True

In [37]:
# Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4,
#5, 6]), perform element-wise addition, subtraction, multiplication, and
# division. Explain the behavior when dividing by zero.

a = np.array([1,2,3])
b = np.array([4,5,6])

a_sum = a + b
a_sum

array([5, 7, 9])

In [38]:
a - b

array([-3, -3, -3])

In [39]:
a*b

array([ 4, 10, 18])

In [40]:
a/b

array([0.25, 0.4 , 0.5 ])

In [41]:
a/0

<ipython-input-41-deacdc4ccabc>:1: RuntimeWarning: divide by zero encountered in divide
  a/0


array([inf, inf, inf])

In [46]:
##Create a 2D array of shape (3, 1) and a 1D array of length 3. Perform
#element-wise addition using broadcasting. Explain how broadcasting rules apply
#in this scenario.

ar = np.array([[1],
               [34],
               [56]])

ar.shape

ar1 = np.array([1,3,5])

ar + ar1

array([[ 2,  4,  6],
       [35, 37, 39],
       [57, 59, 61]])

In [47]:
#Given a 4x4 array of random integers, use indexing and slicing
#to extract:

#o The entire second row
##]o The last column
#o The subarray consisting of the first two rows and first two columns

array = np.random.randint(1,50, size=(4,4))
array

array([[42, 27, 34, 41],
       [ 3, 21, 38, 32],
       [39, 23,  6, 24],
       [ 1, 43, 27, 39]])

In [48]:
array[1,:]

array([ 3, 21, 38, 32])

In [49]:
array[:,3]

array([41, 32, 24, 39])

In [50]:
array[0:2,0:2]

array([[42, 27],
       [ 3, 21]])

In [52]:
#Create a random 4x4 matrix and use NumPy to compute its
#eigenvalues and eigenvectors. Verify the eigenvalues by reconstructing the
#matrix.

matrix =np.random.rand(4,4)
matrix

array([[0.14448306, 0.37460793, 0.45179218, 0.56793752],
       [0.65136067, 0.13083089, 0.41564472, 0.44393738],
       [0.28905253, 0.93681839, 0.37534112, 0.73568427],
       [0.51892539, 0.52300365, 0.26082425, 0.3925395 ]])

In [55]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

[ 1.77805674+0.j         -0.3486756 +0.23190175j -0.3486756 -0.23190175j
 -0.03751097+0.j        ]
[[-0.43623375+0.j         -0.08602716-0.4402932j  -0.08602716+0.4402932j
   0.01914012+0.j        ]
 [-0.45390864+0.j         -0.54756872+0.03039876j -0.54756872-0.03039876j
  -0.2578089 +0.j        ]
 [-0.63088336+0.j          0.61182984+0.j          0.61182984-0.j
  -0.66942853+0.j        ]
 [-0.45349008+0.j          0.12894632+0.32714328j  0.12894632-0.32714328j
   0.69644358+0.j        ]]


In [57]:
reconstructed_matrix = eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors)
reconstructed_matrix

array([[0.14448306-6.37412953e-18j, 0.37460793+1.19296813e-16j,
        0.45179218-3.38763781e-17j, 0.56793752+3.76119842e-18j],
       [0.65136067-1.65023093e-17j, 0.13083089+7.32052061e-17j,
        0.41564472-3.58569097e-17j, 0.44393738-5.74260687e-19j],
       [0.28905253+3.67232310e-17j, 0.93681839+1.67687838e-16j,
        0.37534112-4.81189368e-17j, 0.73568427+1.02129115e-17j],
       [0.51892539+1.51162933e-17j, 0.52300365+1.04184619e-16j,
        0.26082425-3.63148071e-17j, 0.3925395 -3.95297875e-18j]])

In [58]:
# Create a 1D array of 27 elements and reshape it into a 3x3x3
#3D array. Flatten it back into a 1D array and compare the flattened array
#with the original.

ar1 = np.arange(0,27)
ar1.shape

(27,)

In [60]:
ar2 = ar1.reshape(3,3,3)
ar2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [61]:
ar3 = ar2.ravel()
ar3

array([ 0,  1,  2, ..., 24, 25, 26])

In [62]:
np.array_equal(ar1,ar3)

True

In [63]:
np.sum(ar1)

351

In [64]:
np.mean(ar1)

13.0

In [65]:
# Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4,
##1). Perform an element-wise operation using broadcasting and explain the
#result. Use np. new axis to achieve the same result without broadcasting.
array_3d = np.array([[[1, 2, 3, 4]], [[5, 6, 7, 8]]])

# Create a 2D array of shape (4, 1)
array_2d = np.array([[10], [20], [30], [40]])

# Perform element-wise operation using broadcasting (addition)
broadcasted_result = array_3d + array_2d.T
broadcasted_result

array([[[11, 22, 33, 44]],

       [[15, 26, 37, 48]]])

In [66]:
array_2d.T

array([[10, 20, 30, 40]])

In [67]:
manualresult = array_3d + array_2d.T[np.newaxis, :, :]
manualresult

array([[[11, 22, 33, 44]],

       [[15, 26, 37, 48]]])

In [69]:
#Create a 4D array of shape (2, 3, 4, 5) with random integers.
#Use advanced slicing to extract a subarray and compute the mean along a
#specified axis.
array_4d = np.random.randint(1, 101, size=(2, 3, 4, 5))
array_4d

array([[[[ 93,  36,  93,  81,  96],
         [  4,  63,   2,  77,  51],
         [ 80,   5,  70,  59,  25],
         [ 60,  57,  86,  40,  32]],

        [[ 73,  42,  41,  21,  21],
         [ 17,  89,  20,  96,  28],
         [ 91,  37,  44,  25,  57],
         [ 98,  26,  87,  90,  83]],

        [[ 97,  38,  93,  63,  69],
         [ 74,  97,  38,  35,  41],
         [ 63,  36,  35,  65,   1],
         [ 70,  69,  25,  67,  87]]],


       [[[ 79,  43,   1,  59,  19],
         [ 72,  95,  63,  73,  18],
         [ 10,  48,  66,  21,  11],
         [100,  43,  32,  44,  54]],

        [[ 82,  84,  23,   5,  66],
         [ 72, 100,  50,  49,  16],
         [  4,  14,  50,  35,  51],
         [ 29,  51,  70,  62,   9]],

        [[ 14,  53,  14,  71,  60],
         [ 32,  24, 100,  52,  25],
         [ 72,  13,  32,  13,  99],
         [ 11,  64,  67,  46,  63]]]])

In [75]:
subarray = array_4d[:, 1, :2, -3:]
subarray

array([[[41, 21, 21],
        [20, 96, 28]],

       [[23,  5, 66],
        [50, 49, 16]]])

In [79]:
mean_along_axis = np.mean(subarray, axis=2)
mean_along_axis

array([[27.66666667, 48.        ],
       [31.33333333, 38.33333333]])

In [80]:
# Generate a large 2D array and demonstrate the use of np. reshape
# () and unravel () to manipulate its shape for various linear algebra operations.

arr_2d = np.random.rand(10,15)
arr_2d

array([[0.74975696, 0.56044066, 0.57366373, ..., 0.12227388, 0.05007182,
        0.1792176 ],
       [0.36308512, 0.72793426, 0.38093636, ..., 0.22430639, 0.34056073,
        0.30125342],
       [0.07387645, 0.53005036, 0.77010148, ..., 0.5451284 , 0.89213954,
        0.43289904],
       ...,
       [0.86665405, 0.91842116, 0.87067437, ..., 0.91557766, 0.24930265,
        0.41734363],
       [0.52950849, 0.72808255, 0.02374142, ..., 0.74841069, 0.02711865,
        0.91274308],
       [0.93333748, 0.86482683, 0.28545233, ..., 0.62021188, 0.35405682,
        0.01147226]])

In [81]:
arr_2d.shape

(10, 15)

In [85]:
arr_2d.mean()

0.5025510104466374

In [87]:
arr_2d.ravel()

array([0.74975696, 0.56044066, 0.57366373, ..., 0.62021188, 0.35405682,
       0.01147226])

In [91]:
arr_2d.reshape(5,5,6)

array([[[7.49756960e-01, 5.60440665e-01, 5.73663730e-01, 3.92568077e-02,
         1.89340431e-01, 6.33460921e-01],
        [1.19760111e-02, 7.48567974e-01, 4.02153763e-01, 9.98742649e-01,
         5.35090264e-01, 9.53517701e-01],
        [1.22273879e-01, 5.00718215e-02, 1.79217605e-01, 3.63085116e-01,
         7.27934263e-01, 3.80936364e-01],
        [6.48600668e-01, 1.37750542e-01, 8.23746561e-01, 1.93330055e-01,
         9.53318031e-01, 4.16530002e-01],
        [9.21626245e-01, 5.59907063e-01, 7.32783842e-02, 2.24306386e-01,
         3.40560730e-01, 3.01253420e-01]],

       [[7.38764517e-02, 5.30050363e-01, 7.70101481e-01, 4.37830262e-01,
         3.52202590e-01, 2.15896838e-01],
        [8.63308339e-01, 3.22102216e-03, 9.99846654e-01, 8.56275115e-01,
         1.68614308e-01, 2.67790698e-03],
        [5.45128403e-01, 8.92139538e-01, 4.32899039e-01, 1.02238482e-01,
         2.79177432e-01, 2.66251488e-01],
        [7.06041569e-01, 7.07745931e-01, 9.71456616e-01, 1.34128827e-01,
     

In [92]:
# Question: Given a 5x5 array of sequential integers, use slicing to:

#o Extract the diagonal elements
#o Replace the elements of the middle row with zeros
#o Flip the array vertically and horizontally

array = np.arange(1, 26).reshape(5, 5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [93]:
diagonal_elements = np.diagonal(array)
diagonal_elements

array([ 1,  7, 13, 19, 25])

In [95]:
array_with_zeros = array.copy()
array_with_zeros[2, :] = 0
array_with_zeros

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 0,  0,  0,  0,  0],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])