<a href="https://colab.research.google.com/github/avikumart/DA-DS-Questions/blob/main/Numpy/Numpy_vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# loop based indexing instea conditional loops
import numpy as np

%timeit
data = np.random.randn(10000000)
result = []
for x in data:
  if x >0:
    result.append(x*2)
  else:
    result.append(x)
result = np.array(result)
result

array([ 0.14632381, -1.86477188, -0.46942604, ..., -2.32933252,
       -0.34163903,  0.34853537])

In [6]:
# boolean indexing method
%timeit
data = np.random.randn(10000000)
result = data[data>0]*2
result

array([3.18390343, 1.0253118 , 0.4369029 , ..., 1.71543703, 0.77634297,
       1.01112492])

In [10]:
# broadcasting for the implicit loops
matrix = np.random.rand(1000,500)
row_means = matrix.mean(axis=1)
centered = np.zeros_like(matrix)
for i in range(matrix.shape[0]):
  centered[i] = matrix[i] - row_means[i]
centered.shape

(1000, 500)

In [13]:
# faster method of the broadcasting
matrix = np.random.rand(1000,500)
row_means = matrix.mean(axis=1)
centered = matrix - row_means[:,np.newaxis]
centered.shape

(1000, 500)

In [14]:
matrix = np.random.rand(1000,500)
row_means = np.mean(matrix,axis=1)
centered = matrix - row_means[:,np.newaxis]
centered.shape

(1000, 500)

In [19]:
# use of the np.where in the vector operations
temps = np.random.uniform(-10,10,100000)
classifs = np.select([temps <0, temps<20, temps >=20],
                     ["freezing","cool","warm"],
                     default="unknown"
                     )
classifs

array(['freezing', 'freezing', 'cool', ..., 'cool', 'cool', 'cool'],
      dtype='<U8')

In [20]:
# use of the np.where here
scores = np.random.randint(0,100,100000)
grades = np.where(scores>90,"A",
                  np.where(scores>80,"B",
                           np.where(scores>70,"C",
                                    np.where(scores>60,"D","F"))))
grades

array(['A', 'F', 'D', ..., 'F', 'D', 'C'], dtype='<U1')

In [21]:
grades2 = np.where(scores >= 60, "pass","fail")

In [22]:
# use np.vectorization for the vectorization of the data
def transformation(x):
  if x < 0:
    return np.sqrt(abs(x))
  else:
    return x**2

In [24]:
vec_trans = np.vectorize(transformation)
data = np.random.randn(100002)
results = vec_trans(data)
results

array([0.85983896, 0.09854973, 0.76611957, ..., 0.53078834, 0.87794348,
       0.38232987])

In [26]:
# clean matrix multiplication using np.einsum()
A = np.random.rand(100,50)
B = np.random.rand(50,70)
C = np.random.rand(100,100)

matrixdot = np.dot(A,B)
matrixdot

array([[12.90486178, 12.13348686, 13.47769957, ..., 13.176564  ,
        11.09787994,  9.7116922 ],
       [11.75340551, 12.36689584, 11.9987177 , ..., 12.06637136,
        11.01471723,  9.85351314],
       [11.86383182, 13.22443273, 12.55469875, ..., 11.1160537 ,
        12.40186105, 10.25108634],
       ...,
       [12.76661694, 12.21569564, 13.97900935, ..., 13.6257201 ,
        11.97086585, 11.94004157],
       [12.88675488, 11.91866178, 13.4187506 , ..., 13.97510693,
        10.71996672, 10.63208153],
       [11.76053653, 11.60407575, 12.51579095, ..., 11.57123797,
        11.12185356,  9.65362031]])

In [29]:
Neweinsum = np.einsum("ij, jk->ik", A,B)
Neweinsum

array([[12.90486178, 12.13348686, 13.47769957, ..., 13.176564  ,
        11.09787994,  9.7116922 ],
       [11.75340551, 12.36689584, 11.9987177 , ..., 12.06637136,
        11.01471723,  9.85351314],
       [11.86383182, 13.22443273, 12.55469875, ..., 11.1160537 ,
        12.40186105, 10.25108634],
       ...,
       [12.76661694, 12.21569564, 13.97900935, ..., 13.6257201 ,
        11.97086585, 11.94004157],
       [12.88675488, 11.91866178, 13.4187506 , ..., 13.97510693,
        10.71996672, 10.63208153],
       [11.76053653, 11.60407575, 12.51579095, ..., 11.57123797,
        11.12185356,  9.65362031]])

In [31]:
# apply along the axis function
data = np.random.rand(1000,50)

def custom_stat(row):
  return (np.max(row) - np.min(row)) / np.median(row)

row_stats = np.apply_along_axis(custom_stat, axis=0, arr=data)
row_stats

array([1.98573953, 2.02689046, 2.02007517, 2.10826818, 1.98462635,
       1.95530512, 1.9626294 , 2.03888174, 1.922504  , 1.94518604,
       1.86868481, 1.97616134, 1.94007525, 1.97289475, 2.05534685,
       1.93967987, 2.20391182, 1.90196224, 1.90148896, 2.07365044,
       2.10068907, 2.00735189, 1.98322046, 2.04413968, 2.00844269,
       1.96293395, 2.01452719, 1.97886055, 2.02517451, 2.08043077,
       2.05115971, 1.86270953, 2.05233396, 1.9704189 , 2.02445012,
       1.99231426, 2.01548282, 1.89958294, 1.88474619, 1.93388371,
       1.97450894, 1.99615483, 1.98496527, 2.0225849 , 1.99830921,
       1.92206611, 1.98980302, 1.92884819, 2.00117052, 1.99223113])